# Generated by Django 5.1.2 on 2024-10-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_product_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Katalog', 'verbose_name_plural': 'Kataloglar'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Rang', 'verbose_name_plural': 'Ranglar'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': "O'lcham", 'verbose_name_plural': "O'lchamlar"},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.category'),
            preserve_default=False,
        ),
    ]
