# Generated by Django 5.1.2 on 2024-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='project.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='project.productsize'),
        ),
    ]
