# Generated by Django 5.1.2 on 2024-11-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pk',)},
        ),
    ]
